### ISSUE TITLE
vscodium for ppc

### ISSUE THREAD

**Issue by bkeys** [lex-ibm/lex-ibm#2]
I saw (and thank you) that you ported vscodium to work on ppc64le, but when I extract it on my ppc64le system I only get vscodium-server; what stops us from having a normal client like other platforms? Is it possible? What would need to be done?

**Comment by OfficialPr0x** [comment]
> Running the UI is actually possible in PPC64LE, but you need to compile Electron first (since there is no public downloadable binaries for it). IBM has a build script for it [here](https://github.com/ppc64le/build-scripts/blob/master/e/electron/electron-22.0.3-ubuntu-22.04.sh). I had to change very little to get it to work with an older version of GLIBC. Once you have the dist.zip, you can use that (and a few changes to the vscodium build scripts) to get an actual VSCodium UI port. I have to mention some of the issues I've found, tho (at least on my system):
> 
> * Can't get the terminal window to work
> * Sometimes fails to launch
> * Not really stable, specially relating to extensions

careful clicking that electron link ;)

**Comment by lex-ibm** [comment]
Well... I've actually found a way of getting VSCodium to build and run the UI on PPC64LE without any issues... I'll see if I can publish that latter. (might take time to get it reviewed)

**Comment by OfficialPr0x** [comment]
Sweet, would love to connect, I have some cool things in play that Id love to meet new dev friends with

**Comment by lex-ibm** [comment]
> Sweet, would love to connect, I have some cool things in play that Id love to meet new dev friends with
Sorry, can't do 🙁 but good luck!
On another topic, PPC64LE patches are in a PR to upstream VSCodium.
